version: "3.9"

services:
  db:
    container_name: postgres
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  books:
    build: .
    container_name: "books"
    depends_on:
      - "db"
    ports:
      - "8080:8080"